// <auto-generated />
namespace Rent_O_Matic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRentalsHisoryToDataBaseAndBuyPriceToCar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRentalsHisoryToDataBaseAndBuyPriceToCar));
        
        string IMigrationMetadata.Id
        {
            get { return "201704020907475_AddRentalsHisoryToDataBaseAndBuyPriceToCar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
