// <auto-generated />
namespace Rent_O_Matic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CarAndStoreNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CarAndStoreNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201704081724191_CarAndStoreNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
